baseURL = "https://atwood.io"
languageCode = "en-us"
title = "Daniel Atwood"

siteDescription = "I build websites for small and starting businesses. And contribute to open source software in my free time."