---
label: Project
hide_body: true
display_field: title
fields:
- type: text
  name: title
  label: Title
- type: datetime
  name: date
  label: Date
- type: text
  name: link
  label: Link
- type: text
  name: src
  label: Repo
- type: list
  name: categories
  label: Categories
pages:
- content/_index.md
